---
version: "2.0"
services:
  server:
    image: ghcr.io/paperclipai/paperclip:sha-6a4e2e1 # https://github.com/paperclipai/paperclip/pkgs/container/paperclip
    expose:
      - port: 3100
        as: 80
        to:
        - global: true
    env:
      - DATABASE_URL=postgresql://paperclip:paperclip@db:5432/paperclip
      - PORT=3100
      - SERVE_UI=true
      - PAPERCLIP_DEPLOYMENT_MODE=authenticated
      - PAPERCLIP_DEPLOYMENT_EXPOSURE=private
      - PAPERCLIP_PUBLIC_URL=http://provider.akash.com # Provider URL
      - BETTER_AUTH_SECRET=3e3d4cfd927be0b953e28879b76a811359f8cba18cc40f7f5ae48d6466203cb9
      - ANTHROPIC_BASE_URL=https://api.akashml.com/anthropic
      - ANTHROPIC_AUTH_TOKEN=akml-...
      - ANTHROPIC_MODEL=openai/gpt-oss-120b
      - API_TIMEOUT_MS=3000000
    params:
      storage:
        paperclip-data:
          mount: /var/lib/postgresql/data
          readOnly: false
  db:
    image: postgres:15-alpine
    expose:
      - port: 5432
        as: 5432
        to:
          - service: server
    env:
      - POSTGRES_USER=paperclip
      - POSTGRES_PASSWORD=paperclip
      - POSTGRES_DB=paperclip
      - PGDATA=/var/lib/postgresql/data/pgdata
    params:
      storage:
        pgdata:
          mount: /var/lib/postgresql/data
          readOnly: false
profiles:
  compute:
    server:
      resources:
        cpu:
          units: 1
        memory:
          size: 1gi
        storage:
          - size: 1Gi
          - name: paperclip-data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3
    db:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
          - name: pgdata
            size: 10Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    dcloud:
      pricing:
        server:
          denom: uact
          amount: 100000
        db:
          denom: uact
          amount: 100000
deployment:
  server:
    dcloud:
      profile: server
      count: 1
  db:
    dcloud:
      profile: db
      count: 1
