---
version: "2.0"
services:
  app:
    image: declab/automatic1111:0.1
    env:
      - "COMMANDLINE_ARGS=--listen --port=8080 --no-half"
      - "LINK_MODEL=https://huggingface.co/danbrown/RevAnimated-v1-2-2/resolve/main/rev-animated-v1-2-2.safetensors"
    expose:
      - port: 8080
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
        storage:
          size: 30Gi
  placement:
    akash:
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1
