---
version: "2.0"
services:
  goosebin:
    image: ghcr.io/ovrclk/goosebin:20210902b
    expose:
      - port: 8000
        as: 80
        to:
          - global: true
  redis:
    image: redis:6.2.5
    expose:
      - port: 6379
        as: 6379
        to:
          - global: true
          - service: goosebin
profiles:
  compute:
    goosebin:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 128Mi
        storage:
          - size: 128mi
    redis:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          - size: 128mi
  placement:
    dcloud:
      pricing:
        goosebin:
          denom: uakt
          amount: 100000
        redis:
          denom: uakt
          amount: 100000
deployment:
  goosebin:
    dcloud:
      profile: goosebin
      count: 1
  redis:
    dcloud:
      profile: redis
      count: 1
